name: CI

on:
  pull_request:
    branches: [ "main", "master" ]
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip, setuptools, wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install project in editable mode
      run: |
        pip install -e ./workshop/upgraded
    - name: Install test dependencies
      run: |
        pip install pytest
    - name: Run tests
      run: |
        pytest workshop/upgraded/guachi/tests
